### ISSUE TITLE
Turn off drones orbiting player

### ISSUE THREAD

**Issue by malomaster** [pseudopulse/BetterDrones#10]
Can you make a possibility to turn off "Drones orbiting player" feature? Sometimes, when you have 20+ drones, the game start lagging up to unplayable state (≈5 FPS or even less), when they all start shooting enemies. Perhaps lags somewhat related to the fact that it used with ≈100 other mods, but when I turn off your mod and restart run, I got far significantly fewer lags caused by drones.

**Comment by pseudopulse** [comment]
it's already disable-able in the config, under "ror1 drone movement"
