### ISSUE TITLE
Orbit Height

### ISSUE THREAD

**Issue by SchwhatNow** [pseudopulse/BetterDrones#4]
Really like the idea of porting the RoR 1 mechanics into 2 but the actual height that drones fly while orbit is active is too low, they get in the way of sight all the time. 

I know you can increase the distance they orbit from you in the config but would it be possible to also have an option that increases the height they maintain while orbiting?

**Comment by pseudopulse** [comment]
added in commit https://github.com/pseudopulse/BetterDrones/commit/6c6b94fa62ea9eb5ee420326217db8667948d6e3
