### ISSUE TITLE
amazing mod with some funny details

### ISSUE THREAD

**Issue by Almph** [pseudopulse/BetterDrones#7]
Thanks a lot for developing such an interesting mod, love it! 
I updated version 1.4.0 today and found that turret wound orbit me too! So funny. If I want to blacklist some drone or turret, a name list of all the drones will be needed for the config file, right?
![屏幕截图 2023-02-04 150741](https://user-images.githubusercontent.com/49363311/216754148-eca025db-6818-4f98-8044-c178a13b8515.png)
 (and I noticed that the flame drone and summoned drones are already in the blacklist...)
By the way, when I enable this mod the game volume seems to be effected, like the audio being shut down. I haven't found the real reason yet...
Thanks again~

**Comment by Nordblum** [comment]
I'm having the same issue where gunner turrets orbit the player after updating to 1.4.0

**Comment by pseudopulse** [comment]
fixed in 1.4.1
